<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Administrator.local" name="TestNgMavenTest" tests="3" failures="1" timestamp="16 Mar 2018 13:08:31 GMT" time="0.026" errors="0">
  <testcase name="demoTest" time="0.007" classname="com.tapzo.testing.Demo"/>
  <testcase name="demoTest2" time="0.001" classname="com.tapzo.testing.Demo"/>
  <testcase name="demoTest3" time="0.001" classname="com.tapzo.testing.Demo">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at com.tapzo.testing.Demo.demoTest3(Demo.java:21)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- demoTest3 -->
</testsuite> <!-- TestNgMavenTest -->
